export const FETCH_PREVIOUSINSURE_REQUEST = 'FETCH_PREVIOUSINSURE_REQUEST';
export const FETCH_PREVIOUSINSURE_SUCCESS = 'FETCH_PREVIOUSINSURE_SUCCESS';
export const FETCH_PREVIOUSINSURE_FAILURE = 'FETCH_PREVIOUSINSURE_FAILURE';
